# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gegen07/dev/projects/data-structures/C/bs-tree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gegen07/dev/projects/data-structures/C/bs-tree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gegen07/dev/projects/data-structures/C/bs-tree/CMakeFiles /home/gegen07/dev/projects/data-structures/C/bs-tree/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gegen07/dev/projects/data-structures/C/bs-tree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BS_TREE

# Build rule for target.
BS_TREE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BS_TREE
.PHONY : BS_TREE

# fast build rule for target.
BS_TREE/fast:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/build
.PHONY : BS_TREE/fast

lib/bs-tree.o: lib/bs-tree.c.o

.PHONY : lib/bs-tree.o

# target to build an object file
lib/bs-tree.c.o:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/lib/bs-tree.c.o
.PHONY : lib/bs-tree.c.o

lib/bs-tree.i: lib/bs-tree.c.i

.PHONY : lib/bs-tree.i

# target to preprocess a source file
lib/bs-tree.c.i:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/lib/bs-tree.c.i
.PHONY : lib/bs-tree.c.i

lib/bs-tree.s: lib/bs-tree.c.s

.PHONY : lib/bs-tree.s

# target to generate assembly for a file
lib/bs-tree.c.s:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/lib/bs-tree.c.s
.PHONY : lib/bs-tree.c.s

lib/data.o: lib/data.c.o

.PHONY : lib/data.o

# target to build an object file
lib/data.c.o:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/lib/data.c.o
.PHONY : lib/data.c.o

lib/data.i: lib/data.c.i

.PHONY : lib/data.i

# target to preprocess a source file
lib/data.c.i:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/lib/data.c.i
.PHONY : lib/data.c.i

lib/data.s: lib/data.c.s

.PHONY : lib/data.s

# target to generate assembly for a file
lib/data.c.s:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/lib/data.c.s
.PHONY : lib/data.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/BS_TREE.dir/build.make CMakeFiles/BS_TREE.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... BS_TREE"
	@echo "... edit_cache"
	@echo "... lib/bs-tree.o"
	@echo "... lib/bs-tree.i"
	@echo "... lib/bs-tree.s"
	@echo "... lib/data.o"
	@echo "... lib/data.i"
	@echo "... lib/data.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

